version: '2'
services:
    web:
        restart: always
        build: ./website
        expost:
            - "8000"
        links:
            - db
        volumes:
            - /usr/src/app
            - /usr/src/app/static
        env_file: .env
        environment:
            DEBUG: 'true'
        command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: xss_db
            MYSQL_ROOT_PASSWORD: root
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./website/static:/usr/share/nginx/website/static
        ports:
          - "10000:10000"
        depends_on:
          - website
